/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITRC20__factory } from "./ITRC20__factory";
export { TronPaySubscription__factory } from "./TronPaySubscription__factory";
